### ISSUE TITLE
Investigate dcr conformance suite failures for dev

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1179]
The dcr conformance suite is failing for dev and nightly:

https://g.codefresh.io/build/65448b9e2db095851e0d601a?step=run_tests_private_key_jwt&tab=output&logs=terminal

**Comment by dbadham-fr** [comment]
The following test is failing:
```
=== Scenario: DCR-005 - Dynamically retrieve a new software client
        Test case: Register software client
                PASS Generate signed software client claims
                PASS Software client register
                PASS Output x-fapi-interaction-id
                PASS Assert status code 201
                PASS Decode client register response
        Test case: Retrieve client credentials grant
                PASS Client credentials grant
        Test case: Retrieve software client
                PASS Software client retrieve
                PASS Assert status code 200
                FAIL Validate client response schema: schema invalid: software_statement: cannot be blank, software_statement: cannot be blank
```

The `software_statement` field is missing from the GET registration response (GET .../register/7e08b66a-776c-41ab-ac9a-b73541dca13e)

This field is added by the ProcessRegistration script, the value is extracted from the IDM ApiClient object's ssa field. Further investigation is required.

**Comment by dbadham-fr** [comment]
Issue is in ProcessRegistration script:
```
groovy.lang.MissingPropertyException: No such property: ssa for class: com.forgerock.sapi.gateway.dcr.models.ApiClient
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:67)
at org.codehaus.groovy.vmplugin.v8.IndyGuardsFiltersAndSignatures.unwrap(IndyGuardsFiltersAndSignatures.java:161)
at org.codehaus.groovy.vmplugin.v8.IndyInterface.fromCache(IndyInterface.java:321)
at ProcessRegistration$_run_closure4.doCall(ProcessRegistration.groovy:277)
```

A change was made to store the `com.forgerock.sapi.gateway.dcr.models.ApiClient` object in the attributes context, previously a json Map was being stored. 

The `software_statement` value needs to be extracted from the object by calling: `apiClient.softwareStatement.getB64EncodedJwtString()`
