### ISSUE TITLE
IG /authorize route failing to load

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1215]
Exception noticed when IG is starting:
```
org.forgerock.openig.handler.router.RouterHandlerException: An error occurred while building the route with the name '04 - Open Banking Authorize endpoint'
	at org.forgerock.openig.handler.router.RouterHandler.buildRoute(RouterHandler.java:302)
	at org.forgerock.openig.handler.router.RouterHandler.load(RouterHandler.java:279)
	at org.forgerock.openig.handler.router.RouterHandler.onAddedFile(RouterHandler.java:411)
	at org.forgerock.openig.handler.router.RouterHandler.onChanges(RouterHandler.java:391)
	at org.forgerock.openig.handler.router.DirectoryMonitor.monitor(DirectoryMonitor.java:114)
	at org.forgerock.openig.handler.router.RouterHandler$Heaplet.lambda$start$0(RouterHandler.java:525)
	at org.forgerock.openig.handler.router.RouterHandler$Heaplet.start(RouterHandler.java:532)
	at org.forgerock.openig.heap.GenericHeaplet.create(GenericHeaplet.java:82)
	at org.forgerock.openig.heap.HeapImpl.extract(HeapImpl.java:477)
	at org.forgerock.openig.heap.HeapImpl.get(HeapImpl.java:424)
	at org.forgerock.openig.heap.HeapImpl.get(HeapImpl.java:417)
	at org.forgerock.openig.heap.HeapImpl.start(HeapImpl.java:282)
	at org.forgerock.openig.http.GatewayHttpApplication.start(GatewayHttpApplication.java:214)
	at org.forgerock.http.vertx.server.ChfApplicationWebHandler.<init>(ChfApplicationWebHandler.java:148)
	at org.forgerock.openig.launcher.Launcher.run(Launcher.java:307)
	at org.forgerock.openig.launcher.Main.main(Main.java:27)
Caused by: org.forgerock.openig.heap.HeapException: Invalid object declaration
	at org.forgerock.openig.heap.HeapImpl.resolve(HeapImpl.java:504)
	at org.forgerock.openig.heap.HeapImpl.resolve(HeapImpl.java:496)
	at org.forgerock.openig.util.JsonValues.lambda$requiredHeapObject$7(JsonValues.java:407)
	at org.forgerock.json.JsonValue.as(JsonValue.java:555)
	at org.forgerock.json.JsonValueFunctions.lambda$listOf$10(JsonValueFunctions.java:269)
	at org.forgerock.json.JsonValue.as(JsonValue.java:555)
	at org.forgerock.openig.filter.ChainHandlerHeaplet.create(ChainHandlerHeaplet.java:56)
	at org.forgerock.openig.heap.GenericHeaplet.create(GenericHeaplet.java:81)
	at org.forgerock.openig.heap.HeapImpl.extract(HeapImpl.java:477)
	at org.forgerock.openig.heap.HeapImpl.get(HeapImpl.java:424)
	at org.forgerock.openig.heap.HeapImpl.resolve0(HeapImpl.java:539)
	at org.forgerock.openig.heap.HeapImpl.resolve(HeapImpl.java:502)
	at org.forgerock.openig.heap.HeapImpl.resolve(HeapImpl.java:496)
	at org.forgerock.openig.heap.HeapImpl.getHandler(HeapImpl.java:680)
	at org.forgerock.openig.handler.router.RouteBuilder.setupRouteHandler(RouteBuilder.java:255)
	at org.forgerock.openig.handler.router.RouteBuilder.build(RouteBuilder.java:184)
	at org.forgerock.openig.handler.router.RouterHandler.buildRoute(RouterHandler.java:299)
	... 15 common frames omitted
Caused by: org.forgerock.json.JsonValueException: /handler/config/filters/4/type: no heaplet available to initialize object
	at org.forgerock.openig.heap.HeapImpl.addDeclaration(HeapImpl.java:379)
	at org.forgerock.openig.heap.HeapImpl.resolve0(HeapImpl.java:537)
	at org.forgerock.openig.heap.HeapImpl.resolve(HeapImpl.java:502)
	... 31 common frames omitted
"
```

The route protecting the AS /authorize endpoint is failing to load. Functional tests continue to pass as the AS passthrough route gets called instead, but this means that our FAPI filters protecting /authorize are not being run.

**Comment by dbadham-fr** [comment]
Bug introduced by https://github.com/SecureApiGateway/secure-api-gateway-ob-uk/pull/467 ,  which has not yet been released. Therefore we do not need to mention this in the release notes.
