### ISSUE TITLE
UnrecoverableAuthenticationException thrown at IG startup

### ISSUE THREAD

**Issue by dbadham-fr** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1377]
The following exception is being observed in the logs at IG startup:
```
exception: "org.forgerock.openig.tools.authentication.UnrecoverableAuthenticationException: callbacks template request failed with status: [Status: 400 Bad Request]
	at org.forgerock.openig.tools.authentication.AgentTreeAuthenticator.processCallbacksTemplate(AgentTreeAuthenticator.java:121)
	at org.forgerock.util.promise.PromiseImpl$1.executeCallback(PromiseImpl.java:434)
	at org.forgerock.util.promise.PromiseImpl$1.handleStateChange(PromiseImpl.java:422)
	at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:538)
	at org.forgerock.util.promise.PromiseImpl.setState(PromiseImpl.java:579)
	at org.forgerock.util.promise.PromiseImpl.tryHandleResult(PromiseImpl.java:267)
	at org.forgerock.util.promise.PromiseImpl.handleResult(PromiseImpl.java:217)
	at org.forgerock.util.promise.PromiseImpl.lambda$handleResult$4(PromiseImpl.java:464)
	at org.forgerock.util.promise.PromiseImpl.lambda$then$2(PromiseImpl.java:346)
	at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:538)
	at org.forgerock.util.promise.PromiseImpl.setState(PromiseImpl.java:579)
	at org.forgerock.util.promise.PromiseImpl.tryHandleResult(PromiseImpl.java:267)
	at org.forgerock.util.promise.PromiseImpl.handleResult(PromiseImpl.java:217)
	at org.forgerock.util.promise.PromiseImpl.lambda$then$2(PromiseImpl.java:346)
	at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:538)
	at org.forgerock.util.promise.PromiseImpl.setState(PromiseImpl.java:579)
	at org.forgerock.util.promise.PromiseImpl.tryHandleResult(PromiseImpl.java:267)
	at org.forgerock.util.promise.PromiseImpl.handleResult(PromiseImpl.java:217)
	at org.forgerock.util.promise.PromiseImpl.lambda$then$2(PromiseImpl.java:346)
	at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:538)
	at org.forgerock.util.promise.PromiseImpl.setState(PromiseImpl.java:579)
	at org.forgerock.util.promise.PromiseImpl.tryHandleResult(PromiseImpl.java:267)
	at org.forgerock.util.promise.PromiseImpl.handleResult(PromiseImpl.java:217)
	at org.forgerock.util.promise.PromiseImpl.lambda$then$2(PromiseImpl.java:346)
	at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:538)
	at org.forgerock.util.promise.PromiseImpl.setState(PromiseImpl.java:579)
	at org.forgerock.util.promise.PromiseImpl.tryHandleResult(PromiseImpl.java:267)
	at org.forgerock.util.promise.PromiseImpl.handleResult(PromiseImpl.java:217)
	at org.forgerock.util.promise.PromiseImpl.lambda$then$2(PromiseImpl.java:346)
	at org.forgerock.util.promise.PromiseImpl.handleCompletion(PromiseImpl.java:538)
	at org.forgerock.util.promise.PromiseImpl.setState(PromiseImpl.java:579)
	at org.forgerock.util.promise.PromiseImpl.tryHandleResult(PromiseImpl.java:267)
	at org.forgerock.util.promise.PromiseImpl.handleResult(PromiseImpl.java:217)
	at org.forgerock.openig.decoration.capture.MessageCapture$EntityCapturerSubscriber.completePromise(MessageCapture.java:486)
	at org.forgerock.openig.decoration.capture.MessageCapture$EntityCapturerSubscriber.onComplete(MessageCapture.java:482)
	at io.reactivex.rxjava3.internal.util.AtomicThrowable.tryTerminateConsumer(AtomicThrowable.java:92)
	at io.reactivex.rxjava3.internal.util.HalfSerializer.onComplete(HalfSerializer.java:82)
	at io.reactivex.rxjava3.internal.subscribers.StrictSubscriber.onComplete(StrictSubscriber.java:109)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatArray$ConcatArraySubscriber.onComplete(FlowableConcatArray.java:113)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatWithMaybe$ConcatWithSubscriber.onComplete(FlowableConcatWithMaybe.java:89)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate$Emitter.onComplete(MaybeCreate.java:119)
	at org.forgerock.http.io.CharsetDecoderFlowableTransformer.lambda$notifyEndOfInput$8(CharsetDecoderFlowableTransformer.java:169)
	at io.reactivex.rxjava3.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:46)
	at io.reactivex.rxjava3.core.Maybe.subscribe(Maybe.java:5375)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatWithMaybe$ConcatWithSubscriber.onComplete(FlowableConcatWithMaybe.java:95)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onComplete(FlowableDoOnEach.java:135)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:258)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onComplete(FlowableConcatMap.java:165)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableDoOnEach$DoOnEachSubscriber.onComplete(FlowableDoOnEach.java:135)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$ConcatMapImmediate.drain(FlowableConcatMap.java:258)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableConcatMap$BaseConcatMapSubscriber.onComplete(FlowableConcatMap.java:165)
	at io.reactivex.rxjava3.internal.subscribers.BasicFuseableSubscriber.onComplete(BasicFuseableSubscriber.java:120)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableTakeWhile$TakeWhileSubscriber.onComplete(FlowableTakeWhile.java:98)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableUsing$UsingSubscriber.onComplete(FlowableUsing.java:144)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onComplete(FlowableSubscribeOn.java:108)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.onComplete(FlowableGenerate.java:196)
	at org.forgerock.http.protocol.BranchingInputStreamEntityContentStrategy.lambda$emitChunks$2(BranchingInputStreamEntityContentStrategy.java:242)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInternalHelper$SimpleGenerator.apply(FlowableInternalHelper.java:45)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableInternalHelper$SimpleGenerator.apply(FlowableInternalHelper.java:36)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate$GeneratorSubscription.request(FlowableGenerate.java:108)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.requestUpstream(FlowableSubscribeOn.java:133)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.onSubscribe(FlowableSubscribeOn.java:90)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableGenerate.subscribeActual(FlowableGenerate.java:51)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15917)
	at io.reactivex.rxjava3.core.Flowable.subscribe(Flowable.java:15863)
	at io.reactivex.rxjava3.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:65)
	at io.reactivex.rxjava3.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:56)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
"
level: "DEBUG"
logger: "org.forgerock.openig.tools.authentication.FallbackAuthenticationService"
message: "Delegating to secondary authentication, primary authentication failed."
```

The service is functioning correctly when falling back to the secondary authentication.

Investigate the primary & secondary authentication and fix IG config to stop the exception being thrown.

**Comment by dbadham-fr** [comment]
We are configuring the AmService to version 7.3.0 but we are running with AM version 7.5.0

The version config is optional, removing the config so that we can use the service discovery mechanism instead.
