### ISSUE TITLE
GET of /rs/open-banking/v4.0.0/pisp/international-scheduled-payments/{{paymentId}} returns 400

### ISSUE THREAD

**Issue by BohoCode** [SecureBankingAccessToolkit/SecureBankingAccessToolkit#1601]
Test Facility Bank returns this to IG;

```
message: "

<--- (response) exchangeId:974bffb8-8950-4307-82b7-8ec3a2911820-14006 - transactionId:b969c3d8-1d96-4442-8f78-9246c3896f9f/0 ---

HTTP/1.1 400 Bad Request
Content-Length: 76
Content-Type: application/json; charset=utf-8
Date: Thu, 28 Nov 2024 15:26:35 GMT

Payment submission '<payment Id here>' can't be found
"
```

Something is broken somewhere. Furthermore we then end up with the Error Handler failing to handle the error;

```
{
errorGroups: [1]
insertId: "d7t29lisxjo2w1p9"
jsonPayload: {
context: "default"
exception: "groovy.json.JsonException: Unable to determine the current character, it is not a string, number, array, or object

The current character read is 'P' with an int value of 80
Unable to determine the current character, it is not a string, number, array, or object
line number 1
index number 0
Payment submission '<payment Id here>' can't be found
^
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValueInternal(JsonParserCharArray.java:214)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeValue(JsonParserCharArray.java:165)
	at org.apache.groovy.json.internal.JsonParserCharArray.decodeFromChars(JsonParserCharArray.java:45)
	at org.apache.groovy.json.internal.JsonParserCharArray.parse(JsonParserCharArray.java:395)
	at org.apache.groovy.json.internal.BaseJsonParser.parse(BaseJsonParser.java:114)
	at groovy.json.JsonSlurper.parseText(JsonSlurper.java:205)
```

**Comment by BohoCode** [comment]
Please ignore. The postman collection was incorrect. It was trying to GET a payment using a payment consent ID
